---

stages:
    - test
    - coverage

variables:
    GIT_SUBMODULE_STRATEGY: recursive
    fennel_ver: 1.1.0
    fenneldoc_ver: v0.1.9

.install_fennel: &fennel |-
    cd "$HOME"
    git clone -q --depth=1 --branch="$fennel_ver" https://git.sr.ht/~technomancy/fennel
    cd fennel || exit -1
    make install
    cd "$CI_PROJECT_DIR"

.install_fenneldoc: &fenneldoc |-
    cd "$HOME"
    git clone -q --depth=1 --branch="$fenneldoc_ver" \
              --recursive https://gitlab.com/andreyorst/fenneldoc.git
    cd fenneldoc || exit -1
    make install
    cd "$CI_PROJECT_DIR"

Test:
    image: alpine:edge
    stage: test
    timeout: 2m
    before_script:
        - >
            apk add -q
            lua5.2 lua5.3 lua5.3-dev lua5.4 luarocks5.3
            git make gcc musl-dev lua-socket
        - export LUA=lua5.3
        - luarocks-5.3 install fennel "$fennel_ver"
        - luarocks-5.3 install luacov
        - luarocks-5.3 install cluacov
        - luarocks-5.3 install luacov-cobertura
        - *fenneldoc
    script:
        - LUAEXECUTABLES="lua5.2 lua5.3 lua5.4" make testall
        - make luacov
        - tail luacov.report
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: coverage/cobertura-coverage.xml
    coverage: '/Total.*\s(\d+.\d+%)$/'
